# Generated by Django 2.0.7 on 2018-07-25 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Hotel'),
        ),
        migrations.AlterField(
            model_name='stanza',
            name='hotelDiAppartenenza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Hotel'),
        ),
    ]
